### ISSUE TITLE
User view shows a page with blank elements for a nonexisting user

### ISSUE THREAD

**Issue by susinda** [wso2/carbon-device-mgt#648] opened 2017-03-16 06:01 UTC
Try https://localhost:9443/devicemgt/user/view?username=nonExistingUser
And the page displays as follows
![usernonexisting-2017-03-16 11-28-57](https://cloud.githubusercontent.com/assets/4962136/23983763/e7b87476-0a3b-11e7-9b07-b57a7833e5ad.png)

**Comment by Kamidu** [comment] 2017-03-21 05:26
@susinda This is because the users created using the creat account/register page does not have any roles other than the internal roles added by the system those internal roles are not listed here. This is the expected view for a user.
So can you please close this issue.
Thanks and Best Regards,

**Comment by rasika** [comment] 2018-01-03 19:10
This is not reproducible in the latest. Hence resolving.

**Closed as completed by rasika** 2018-01-03 19:10 UTC
Labels: enhancement
